[versions]

componentsResources = "1.10.0"
foundation = "1.10.0"
kfirebaseAuth = "2.1.0"
kfirebaseCore = "2.1.2"
kotlin = "2.3.0"
compose = "1.10.0"
agp = "9.0.0"
kmmCrypto = "2.0.2"
androidx-activityCompose = "1.12.2"
core = "1.7.0"
material3 = "1.10.0-alpha05"
maven-publish = "0.36.0"
google-services = "4.4.4"
playServicesAuth = "21.5.0"
kotlinxCoroutinesCore = "1.10.2"
runtime = "1.10.0"
startupRuntime = "1.2.0"
credentialsPlayServicesAuth = "1.5.0"
googleid = "1.2.0"
uiToolingPreview = "1.10.0"
[libraries]

androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "componentsResources" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "foundation" }
kfirebase-auth = { module = "io.github.the-best-is-best:kfirebase-auth", version.ref = "kfirebaseAuth" }
kfirebase-core = { module = "io.github.the-best-is-best:kfirebase-core", version.ref = "kfirebaseCore" }
kmm-crypto = { module = "io.github.the-best-is-best:kmm-crypto", version.ref = "kmmCrypto" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }

androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentialsPlayServicesAuth" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "runtime" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "uiToolingPreview" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }

[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
